changes the configuration to use a polynomial to define the mapping o…
lsst-ts/ts_config_eas pull request #3
Opened 2021-01-30 01:57 UTC by colinwinslow

…f voltage readings onto telemetry units, and adds documentaion.

2021-02-01 16:16 UTC, patrickingraham requested changes

2021-02-01 16:16 UTC, patrickingraham commented on AdamSensors/v1/2020_homeoffice_pandemic_test.yaml
> +analog_input_3_coefficients: [344738, 0]
Do you care about whether things are floats/ints ?
Does this have a type in the schema? Probably worth matching that if so..

2021-02-01 16:16 UTC, patrickingraham commented on AdamSensors/v1/_labels.yaml
> +test: homeoffice_pandemic_test.yaml
how about `initial_test_config.yaml`

2021-02-15 15:26 UTC, tribeiro commented on AdamSensors/v1/_labels.yaml
> +test: homeoffice_pandemic_test.yaml
@colinwinslow , can you rename the file please?

2021-02-15 15:27 UTC, tribeiro commented on AdamSensors/v1/homeoffice_pandemic_test.yaml
> +# The AdamSensors CSC reads voltages off of the ADAM 6024's six analog input channels, in
Please, rename this file to something like `initial_test_config.yaml`, as suggested above?

2021-02-15 15:28 UTC, tribeiro requested changes
Please, rename the configuration and update the labels file.

2021-02-15 19:09 UTC, tribeiro approved these changes

2021-02-15 19:22 UTC, patrickingraham approved these changes
Changes addressed.

2021-02-15 19:39 UTC, merged